### ISSUE TITLE
Get  all active product Api not working correctly (/product/getallactiveproduct)

### ISSUE THREAD

**Issue by NASWEEF** [navas-infobreez/-Customer-Diary-Server#10]
Forwarding to error page from request [/product/getallactiveproduct] due to exception [Could not obtain transaction-synchronized Session for current thread; nested exception is org.hibernate.HibernateException: Could not obtain transaction-synchronized Session for current thread]

**Comment by navas-infobreez** [comment]
@transaction is missing
